- name: Cucumber Report to Annotations
  # You may pin to the exact commit or the version.
  # uses: deblockt/cucumber-report-annotations-action@6752fe2c8e2640f9c98687d7b1782e3755fbe434
  uses: deblockt/cucumber-report-annotations-action@v1.16
  with:
    # github token
    access-token: 
    # glob to cucumber json files
    path: # default is **/cucumber-report.json
    # the check status to use on cucumber error. Can be 'success', 'neutral' or 'failure'
    check-status-on-error: # default is failure
    # the check status to use on cucumber undefined steps. Can be 'success', 'neutral' or 'failure'
    check-status-on-undefined: # default is success
    # the check status to use on cucumber pending steps. Can be 'success', 'neutral' or 'failure'
    check-status-on-pending: # default is success
    # the annotation status on error. Can be 'notice', 'warning', 'failure'
    annotation-status-on-error: # optional, default is failure
    # the annotation status on undefined steps. Can be 'notice', 'warning', 'failure'. if this property is not set, no annotation will be generated for undefined steps
    annotation-status-on-undefined: # optional
    # the annotation status on pending steps. Can be 'notice', 'warning', 'failure'. if this property is not set, no annotation will be generated for pending steps
    annotation-status-on-pending: # optional
    # if it is set to true, the number of errors will be indicated on the check title (visible on the pr check)
    show-number-of-error-on-check-title: # optional, default is true
    # if it is set to true, a full summary report will be display for each feature file.
    show-global-summary-report: # optional, default is false
    # indicate the number of test in error to fail the build. If the value is -1 this action will never fail the build.
    number-of-test-error-to-fail-job: # optional, default is -1
    # the name of the check
    name: # optional, default is Cucumber report
